### PR TITLE
• Add Support to SSL via PopUpMenu

### PR DESCRIPTION
**Pull request by Valdemar-VDSC**
• Auto add Channel to sendChannel menu
• Correction when send NOTIFY to PostgreSQL

### CODE REVIEW

**Review by gregorplop — CHANGES_REQUESTED** [review]
Hi, I see you've changed the sendChannel control from a ComboBox to a non-editable PopupMenu.
By doing this, you assume that the client who wants to send a test message to a channel should always want to be listening to that channel also. This does not necessarily happen in practice (in my own actual implementation, it certainly doesn't).
Think of it like this: by doing so, you're limiting the functionality of the app, without gaining anything in return. Why would you want it?  :)
My suggestion would be to just leave anything regarding the sendChannel menu as it was 
(including the added sendChannel.RemoveRow statement)

I've also noticed the change to the NOTIFY statement, I guess for accommodating channel names containing a space or mixed case. I'd discourage such practices if anyone asked for my opinion, but as long as it keeps working, I'm fine with the change.

**Comment by Valdemar-VDSC** [comment]
The change into NOTIFY command is to be able to work through a VPN with an PostgreSQL using SSL. I Notice that without quotting the channel, the command vanished.

**Comment by gregorplop** [comment]
that's something I'd never would have guessed :)
how shall we proceed with the merge request?
have you decided what you want to do with the sendChannel issue?

**Comment by gregorplop** [comment]
hi, since I haven't heard from you, I'll close the pull request.
I think a lesson learned from this experience is that each fork resulting in a merge request should concern one and only one change. in this case the ssl property menu and the new notify statement were acceptable, but the sendChannel changing from combo to popup was not.
thanks for your time!

**Pull request closed without merging**
